FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine
WORKDIR /home/app

COPY src src
COPY tests tests

RUN apk add gcompat

RUN dotnet test tests/Consumer.Tests/Consumer.Tests.csproj
RUN dotnet test tests/Provider.Tests/Provider.Tests.csproj
